# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Default

steps:

- script: |
    docker-compose build
    docker-compose push
    docker stack deploy --compose-file docker-compose.yml combined-svcs
  displayName: 'Run a multi-line script'
